# Auto-generated from Community Dragon TFT data for Set 17.
# Riot API names may differ from in-game display names.

components = {
    "TFT_Item_BFSword",
    "TFT_Item_RecurveBow",
    "TFT_Item_NeedlesslyLargeRod",
    "TFT_Item_TearOfTheGoddess",
    "TFT_Item_ChainVest",
    "TFT_Item_NegatronCloak",
    "TFT_Item_GiantsBelt",
    "TFT_Item_SparringGloves",
    "TFT_Item_Spatula",
    "TFT_Item_FryingPan",
}

itemToComponent = {
    # --- STANDARD CRAFTABLE ITEMS ---
    "TFT_Item_AdaptiveHelm": ["TFT_Item_NegatronCloak", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_ArchangelsStaff": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_Bloodthirster": ["TFT_Item_BFSword", "TFT_Item_NegatronCloak"],
    "TFT_Item_BlueBuff": ["TFT_Item_TearOfTheGoddess", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_BrambleVest": ["TFT_Item_ChainVest", "TFT_Item_ChainVest"],
    "TFT_Item_Crownguard": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_ChainVest"],
    "TFT_Item_Deathblade": ["TFT_Item_BFSword", "TFT_Item_BFSword"],
    "TFT_Item_DragonsClaw": ["TFT_Item_NegatronCloak", "TFT_Item_NegatronCloak"],
    "TFT_Item_ForceOfNature": ["TFT_Item_Spatula", "TFT_Item_Spatula"],
    "TFT_Item_FrozenHeart": ["TFT_Item_TearOfTheGoddess", "TFT_Item_ChainVest"],
    "TFT_Item_GargoyleStoneplate": ["TFT_Item_ChainVest", "TFT_Item_NegatronCloak"],
    "TFT_Item_GuardianAngel": ["TFT_Item_BFSword", "TFT_Item_ChainVest"],
    "TFT_Item_GuinsoosRageblade": ["TFT_Item_RecurveBow", "TFT_Item_NeedlesslyLargeRod"],
    "TFT_Item_HextechGunblade": ["TFT_Item_BFSword", "TFT_Item_NeedlesslyLargeRod"],
    "TFT_Item_InfinityEdge": ["TFT_Item_BFSword", "TFT_Item_SparringGloves"],
    "TFT_Item_IonicSpark": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_NegatronCloak"],
    "TFT_Item_JeweledGauntlet": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_SparringGloves"],
    "TFT_Item_LastWhisper": ["TFT_Item_RecurveBow", "TFT_Item_SparringGloves"],
    "TFT_Item_Leviathan": ["TFT_Item_RecurveBow", "TFT_Item_GiantsBelt"],
    "TFT_Item_MadredsBloodrazor": ["TFT_Item_BFSword", "TFT_Item_RecurveBow"],
    "TFT_Item_Morellonomicon": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_GiantsBelt"],
    "TFT_Item_NightHarvester": ["TFT_Item_ChainVest", "TFT_Item_SparringGloves"],
    "TFT_Item_PowerGauntlet": ["TFT_Item_GiantsBelt", "TFT_Item_SparringGloves"],
    "TFT_Item_Quicksilver": ["TFT_Item_SparringGloves", "TFT_Item_NegatronCloak"],
    "TFT_Item_RabadonsDeathcap": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_NeedlesslyLargeRod"],
    "TFT_Item_RapidFireCannon": ["TFT_Item_RecurveBow", "TFT_Item_RecurveBow"],
    "TFT_Item_RedBuff": ["TFT_Item_ChainVest", "TFT_Item_GiantsBelt"],
    "TFT_Item_Redemption": ["TFT_Item_TearOfTheGoddess", "TFT_Item_GiantsBelt"],
    "TFT_Item_RunaansHurricane": ["TFT_Item_NegatronCloak", "TFT_Item_RecurveBow"],
    "TFT_Item_SpearOfShojin": ["TFT_Item_BFSword", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_SpectralGauntlet": ["TFT_Item_NegatronCloak", "TFT_Item_GiantsBelt"],
    "TFT_Item_StatikkShiv": ["TFT_Item_RecurveBow", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_SteraksGage": ["TFT_Item_BFSword", "TFT_Item_GiantsBelt"],
    "TFT_Item_TacticiansRing": ["TFT_Item_Spatula", "TFT_Item_FryingPan"],
    "TFT_Item_TacticiansScepter": ["TFT_Item_FryingPan", "TFT_Item_FryingPan"],
    "TFT_Item_ThiefsGloves": ["TFT_Item_SparringGloves", "TFT_Item_SparringGloves"],
    "TFT_Item_TitansResolve": ["TFT_Item_ChainVest", "TFT_Item_RecurveBow"],
    "TFT_Item_UnstableConcoction": ["TFT_Item_TearOfTheGoddess", "TFT_Item_SparringGloves"],
    "TFT_Item_WarmogsArmor": ["TFT_Item_GiantsBelt", "TFT_Item_GiantsBelt"],
    # --- SET 17 EMBLEMS (API trait names) ---
    "TFT17_Item_ASTraitEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_RecurveBow"],
    "TFT17_Item_AssassinTraitEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_SparringGloves"],
    "TFT17_Item_AstronautEmblemItem": ["TFT_Item_Spatula", "TFT_Item_ChainVest"],
    "TFT17_Item_DRXEmblemItem": ["TFT_Item_Spatula", "TFT_Item_SparringGloves"],
    "TFT17_Item_DarkStarEmblemItem": ["TFT_Item_Spatula", "TFT_Item_BFSword"],
    "TFT17_Item_FavoredEmblemItem": ["TFT_Item_Spatula", "TFT_Item_NegatronCloak"],
    "TFT17_Item_FlexTraitEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_NeedlesslyLargeRod"],
    "TFT17_Item_HPTankEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_GiantsBelt"],
    "TFT17_Item_MeleeTraitEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_BFSword"],
    "TFT17_Item_PrimordianEmblemItem": ["TFT_Item_Spatula", "TFT_Item_GiantsBelt"],
    "TFT17_Item_PulsefireEmblemItem": ["TFT_Item_Spatula", "TFT_Item_RecurveBow"],
    "TFT17_Item_ResistTankEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_ChainVest"],
    "TFT17_Item_ShieldTankEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_NegatronCloak"],
    "TFT17_Item_SpaceGrooveEmblemItem": ["TFT_Item_Spatula", "TFT_Item_TearOfTheGoddess"],
    "TFT17_Item_StargazerEmblemItem": ["TFT_Item_Spatula", "TFT_Item_NeedlesslyLargeRod"],
    "TFT17_Item_SummonTraitEmblemItem": ["TFT_Item_FryingPan", "TFT_Item_TearOfTheGoddess"],
}
