# Auto-generated from Community Dragon TFT data for Set 18.
# Riot API names may differ from in-game display names.

components = {
    "DA_Component_BFSword",
    "DA_Component_RecurveBow",
    "DA_Component_NeedlesslyLargeRod",
    "DA_Component_TearOfTheGoddess",
    "DA_Component_ChainVest",
    "DA_Component_NegatronCloak",
    "DA_Component_GiantsBelt",
    "DA_Component_SparringGloves",
    "DA_Component_Spatula",
    "DA_Component_FryingPan",
    "TFT_Item_BFSword",
    "TFT_Item_RecurveBow",
    "TFT_Item_NeedlesslyLargeRod",
    "TFT_Item_TearOfTheGoddess",
    "TFT_Item_ChainVest",
    "TFT_Item_NegatronCloak",
    "TFT_Item_GiantsBelt",
    "TFT_Item_SparringGloves",
    "TFT_Item_Spatula",
    "TFT_Item_FryingPan",
}

componentAliases = {
    "TFT_Item_BFSword": "DA_Component_BFSword",
    "DA_Component_BFSword": "DA_Component_BFSword",
    "TFT_Item_RecurveBow": "DA_Component_RecurveBow",
    "DA_Component_RecurveBow": "DA_Component_RecurveBow",
    "TFT_Item_NeedlesslyLargeRod": "DA_Component_NeedlesslyLargeRod",
    "DA_Component_NeedlesslyLargeRod": "DA_Component_NeedlesslyLargeRod",
    "TFT_Item_TearOfTheGoddess": "DA_Component_TearOfTheGoddess",
    "DA_Component_TearOfTheGoddess": "DA_Component_TearOfTheGoddess",
    "TFT_Item_ChainVest": "DA_Component_ChainVest",
    "DA_Component_ChainVest": "DA_Component_ChainVest",
    "TFT_Item_NegatronCloak": "DA_Component_NegatronCloak",
    "DA_Component_NegatronCloak": "DA_Component_NegatronCloak",
    "TFT_Item_GiantsBelt": "DA_Component_GiantsBelt",
    "DA_Component_GiantsBelt": "DA_Component_GiantsBelt",
    "TFT_Item_SparringGloves": "DA_Component_SparringGloves",
    "DA_Component_SparringGloves": "DA_Component_SparringGloves",
    "TFT_Item_Spatula": "DA_Component_Spatula",
    "DA_Component_Spatula": "DA_Component_Spatula",
    "TFT_Item_FryingPan": "DA_Component_FryingPan",
    "DA_Component_FryingPan": "DA_Component_FryingPan",
}

itemToComponent = {
    # --- SET 18 STANDARD CRAFTABLE ITEMS (DA_) ---
    "DA_AdaptiveHelm": ["DA_Component_TearOfTheGoddess", "DA_Component_NegatronCloak"],
    "DA_ArchangelsStaff": ["DA_Component_NeedlesslyLargeRod", "DA_Component_TearOfTheGoddess"],
    "DA_Bloodthirster": ["DA_Component_BFSword", "DA_Component_NegatronCloak"],
    "DA_BlueBuff": ["DA_Component_TearOfTheGoddess", "DA_Component_TearOfTheGoddess"],
    "DA_BrambleVest": ["DA_Component_ChainVest", "DA_Component_ChainVest"],
    "DA_Crownguard": ["DA_Component_NeedlesslyLargeRod", "DA_Component_ChainVest"],
    "DA_Deathblade": ["DA_Component_BFSword", "DA_Component_BFSword"],
    "DA_DragonsClaw": ["DA_Component_NegatronCloak", "DA_Component_NegatronCloak"],
    "DA_EdgeOfNight": ["DA_Component_BFSword", "DA_Component_ChainVest"],
    "DA_Evenshroud": ["DA_Component_NegatronCloak", "DA_Component_GiantsBelt"],
    "DA_GargoyleStoneplate": ["DA_Component_ChainVest", "DA_Component_NegatronCloak"],
    "DA_GiantSlayer": ["DA_Component_RecurveBow", "DA_Component_BFSword"],
    "DA_GuinsoosRageblade": ["DA_Component_RecurveBow", "DA_Component_NeedlesslyLargeRod"],
    "DA_HandOfJustice": ["DA_Component_TearOfTheGoddess", "DA_Component_SparringGloves"],
    "DA_HextechGunblade": ["DA_Component_BFSword", "DA_Component_NeedlesslyLargeRod"],
    "DA_InfinityEdge": ["DA_Component_BFSword", "DA_Component_SparringGloves"],
    "DA_IonicSpark": ["DA_Component_NeedlesslyLargeRod", "DA_Component_NegatronCloak"],
    "DA_JeweledGauntlet": ["DA_Component_SparringGloves", "DA_Component_NeedlesslyLargeRod"],
    "DA_KrakensFury": ["DA_Component_RecurveBow", "DA_Component_NegatronCloak"],
    "DA_LastWhisper": ["DA_Component_RecurveBow", "DA_Component_SparringGloves"],
    "DA_Morellonomicon": ["DA_Component_GiantsBelt", "DA_Component_NeedlesslyLargeRod"],
    "DA_NashorsTooth": ["DA_Component_RecurveBow", "DA_Component_GiantsBelt"],
    "DA_ProtectorsVow": ["DA_Component_ChainVest", "DA_Component_TearOfTheGoddess"],
    "DA_Quicksilver": ["DA_Component_NegatronCloak", "DA_Component_SparringGloves"],
    "DA_RabadonsDeathcap": ["DA_Component_NeedlesslyLargeRod", "DA_Component_NeedlesslyLargeRod"],
    "DA_RedBuff": ["DA_Component_RecurveBow", "DA_Component_RecurveBow"],
    "DA_SpearOfShojin": ["DA_Component_TearOfTheGoddess", "DA_Component_BFSword"],
    "DA_SpiritVisage": ["DA_Component_GiantsBelt", "DA_Component_TearOfTheGoddess"],
    "DA_SteadfastHeart": ["DA_Component_ChainVest", "DA_Component_SparringGloves"],
    "DA_SteraksGage": ["DA_Component_BFSword", "DA_Component_GiantsBelt"],
    "DA_StrikersFlail": ["DA_Component_GiantsBelt", "DA_Component_SparringGloves"],
    "DA_SunfireCape": ["DA_Component_ChainVest", "DA_Component_GiantsBelt"],
    "DA_TacticiansCape": ["DA_Component_Spatula", "DA_Component_FryingPan"],
    "DA_TacticiansCrown": ["DA_Component_Spatula", "DA_Component_Spatula"],
    "DA_TacticiansShield": ["DA_Component_FryingPan", "DA_Component_FryingPan"],
    "DA_ThiefsGloves": ["DA_Component_SparringGloves", "DA_Component_SparringGloves"],
    "DA_TitansResolve": ["DA_Component_RecurveBow", "DA_Component_ChainVest"],
    "DA_VoidStaff": ["DA_Component_RecurveBow", "DA_Component_TearOfTheGoddess"],
    "DA_WarmogsArmor": ["DA_Component_GiantsBelt", "DA_Component_GiantsBelt"],
    # --- SET 18 EMBLEMS ---
    "DA_18_EmblemBlackthorn": ["DA_Component_Spatula", "DA_Component_GiantsBelt"],
    "DA_18_EmblemBlossom": ["DA_Component_Spatula", "DA_Component_NeedlesslyLargeRod"],
    "DA_18_EmblemBrawler": ["DA_Component_FryingPan", "DA_Component_GiantsBelt"],
    "DA_18_EmblemElderwood": ["DA_Component_Spatula", "DA_Component_ChainVest"],
    "DA_18_EmblemExecutioner": ["DA_Component_FryingPan", "DA_Component_SparringGloves"],
    "DA_18_EmblemFae": ["DA_Component_Spatula", "DA_Component_BFSword"],
    "DA_18_EmblemHunter": ["DA_Component_FryingPan", "DA_Component_BFSword"],
    "DA_18_EmblemInferno": ["DA_Component_Spatula", "DA_Component_RecurveBow"],
    "DA_18_EmblemInvoker": ["DA_Component_FryingPan", "DA_Component_TearOfTheGoddess"],
    "DA_18_EmblemLunar": ["DA_Component_Spatula", "DA_Component_TearOfTheGoddess"],
    "DA_18_EmblemPrimal": ["DA_Component_Spatula", "DA_Component_SparringGloves"],
    "DA_18_EmblemRapidfire": ["DA_Component_FryingPan", "DA_Component_RecurveBow"],
    "DA_18_EmblemSlayer": ["DA_Component_FryingPan", "DA_Component_NegatronCloak"],
    "DA_18_EmblemSpellweaver": ["DA_Component_FryingPan", "DA_Component_NeedlesslyLargeRod"],
    "DA_18_EmblemSprykin": ["DA_Component_Spatula", "DA_Component_NegatronCloak"],
    "DA_18_EmblemVanguard": ["DA_Component_FryingPan", "DA_Component_ChainVest"],
    # --- LEGACY TFT_Item_ RECIPES ---
    "TFT_Item_AdaptiveHelm": ["TFT_Item_NegatronCloak", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_ArchangelsStaff": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_Bloodthirster": ["TFT_Item_BFSword", "TFT_Item_NegatronCloak"],
    "TFT_Item_BlueBuff": ["TFT_Item_TearOfTheGoddess", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_BrambleVest": ["TFT_Item_ChainVest", "TFT_Item_ChainVest"],
    "TFT_Item_Crownguard": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_ChainVest"],
    "TFT_Item_Deathblade": ["TFT_Item_BFSword", "TFT_Item_BFSword"],
    "TFT_Item_DragonsClaw": ["TFT_Item_NegatronCloak", "TFT_Item_NegatronCloak"],
    "TFT_Item_ForceOfNature": ["TFT_Item_Spatula", "TFT_Item_Spatula"],
    "TFT_Item_FrozenHeart": ["TFT_Item_TearOfTheGoddess", "TFT_Item_ChainVest"],
    "TFT_Item_GargoyleStoneplate": ["TFT_Item_ChainVest", "TFT_Item_NegatronCloak"],
    "TFT_Item_GuardianAngel": ["TFT_Item_BFSword", "TFT_Item_ChainVest"],
    "TFT_Item_GuinsoosRageblade": ["TFT_Item_RecurveBow", "TFT_Item_NeedlesslyLargeRod"],
    "TFT_Item_HextechGunblade": ["TFT_Item_BFSword", "TFT_Item_NeedlesslyLargeRod"],
    "TFT_Item_InfinityEdge": ["TFT_Item_BFSword", "TFT_Item_SparringGloves"],
    "TFT_Item_IonicSpark": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_NegatronCloak"],
    "TFT_Item_JeweledGauntlet": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_SparringGloves"],
    "TFT_Item_LastWhisper": ["TFT_Item_RecurveBow", "TFT_Item_SparringGloves"],
    "TFT_Item_Leviathan": ["TFT_Item_RecurveBow", "TFT_Item_GiantsBelt"],
    "TFT_Item_MadredsBloodrazor": ["TFT_Item_BFSword", "TFT_Item_RecurveBow"],
    "TFT_Item_Morellonomicon": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_GiantsBelt"],
    "TFT_Item_NightHarvester": ["TFT_Item_ChainVest", "TFT_Item_SparringGloves"],
    "TFT_Item_PowerGauntlet": ["TFT_Item_GiantsBelt", "TFT_Item_SparringGloves"],
    "TFT_Item_Quicksilver": ["TFT_Item_SparringGloves", "TFT_Item_NegatronCloak"],
    "TFT_Item_RabadonsDeathcap": ["TFT_Item_NeedlesslyLargeRod", "TFT_Item_NeedlesslyLargeRod"],
    "TFT_Item_RapidFireCannon": ["TFT_Item_RecurveBow", "TFT_Item_RecurveBow"],
    "TFT_Item_RedBuff": ["TFT_Item_ChainVest", "TFT_Item_GiantsBelt"],
    "TFT_Item_Redemption": ["TFT_Item_TearOfTheGoddess", "TFT_Item_GiantsBelt"],
    "TFT_Item_RunaansHurricane": ["TFT_Item_NegatronCloak", "TFT_Item_RecurveBow"],
    "TFT_Item_SpearOfShojin": ["TFT_Item_BFSword", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_SpectralGauntlet": ["TFT_Item_NegatronCloak", "TFT_Item_GiantsBelt"],
    "TFT_Item_StatikkShiv": ["TFT_Item_RecurveBow", "TFT_Item_TearOfTheGoddess"],
    "TFT_Item_SteraksGage": ["TFT_Item_BFSword", "TFT_Item_GiantsBelt"],
    "TFT_Item_TacticiansRing": ["TFT_Item_Spatula", "TFT_Item_FryingPan"],
    "TFT_Item_TacticiansScepter": ["TFT_Item_FryingPan", "TFT_Item_FryingPan"],
    "TFT_Item_ThiefsGloves": ["TFT_Item_SparringGloves", "TFT_Item_SparringGloves"],
    "TFT_Item_TitansResolve": ["TFT_Item_ChainVest", "TFT_Item_RecurveBow"],
    "TFT_Item_UnstableConcoction": ["TFT_Item_TearOfTheGoddess", "TFT_Item_SparringGloves"],
    "TFT_Item_WarmogsArmor": ["TFT_Item_GiantsBelt", "TFT_Item_GiantsBelt"],
}
